import type { Product } from './CartContext';

export const products: Product[] = [
  {
    id: 1,
    name: 'Bouquet Romántico',
    price: 50000,
    category: 'romantico',
    rating: 4.9,
    reviews: 128,
    badge: 'Más vendido',
    description: 'Bouquet de rosas rojas premium, ideal para sorprender a alguien especial.',
    image: '/images/products/ramo1.jpeg',
  },
  {
    id: 2,
    name: 'Corazón Kinder Love',
    price: 23000,
    category: 'romantico',
    rating: 4.8,
    reviews: 95,
    description: 'Elegante arreglo de rosas rojas en jarrón de cerámica blanca.',
    image: '/images/products/corazon1.jpeg',
  },
  {
    id: 3,
    name: 'Corazon con Milka',
    price: 23000,
    category: 'romantico',
    rating: 4.7,
    reviews: 67,
    badge: 'Nuevo',
    description: 'Arreglo floral en forma de corazón con sorpresa Milka incluida.',
    image: '/images/products/corazon2.jpeg',
  },
  {
    id: 4,
    name: 'Box Cumpleaños',
    price: 80000,
    category: 'cumpleanos',
    rating: 4.9,
    reviews: 203,
    badge: 'Popular',
    description: 'Box especial de cumpleaños armado con amor, incluye productos seleccionados y tarjeta.',
    image: '/images/products/boxcumple.jpeg',
  },
  {
    id: 6,
    name: 'Box romántico',
    price: 40000,
    category: 'aniversario',
    rating: 5.0,
    reviews: 41,
    badge: 'Premium',
    description: 'Box romántico con osito de peluche y tarjeta personalizada incluida.',
    image: '/images/products/oso1.jpeg',
  },
  {
    id: 7,
    name: 'Stich Surprise',
    price: 60000,
    originalPrice: 75000,
    category: 'aniversario',
    rating: 4.9,
    reviews: 72,
    badge: 'Oferta',
    description: 'El querido Stitch de Lilo & Stitch, ideal para sorprender a alguien especial.',
    image: '/images/products/stich1.jpeg',
  },
  {
    id: 8,
    name: 'Box Romántico Deluxe',
    price: 80000,
    originalPrice: 90000,
    category: 'romantico',
    rating: 4.9,
    reviews: 54,
    badge: 'Para enamorados',
    description: 'Combo romántico: peluche Lotso con bouquet de rosas incluido.',
    image: '/images/products/lotso1.jpeg',
  },
  {
    id: 10,
    name: 'Corazón para Cumpleaños',
    price: 3490,
    category: 'cumpleanos',
    rating: 4.7,
    reviews: 112,
    description: 'Arreglo en forma de corazón especial para regalar en un cumpleaños.',
    image: '/images/products/corazon2.jpeg',
  },
  {
    id: 11,
    name: 'Corazón de Rosas',
    price: 6490,
    category: 'aniversario',
    rating: 4.8,
    reviews: 33,
    description: 'Arreglo en forma de corazón, el regalo más romántico para una ocasión especial.',
    image: '/images/products/corazon1.jpeg',
  },
];
